/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_test_24 (
    input clk,
    input rst,
    input [7:0] alu,
    output reg [7:0] testA,
    output reg [7:0] testB,
    output reg [5:0] alufn,
    input reset
  );
  
  
  
  
  localparam CMPEQTEST0_state = 4'd0;
  localparam CMPEQTEST1_state = 4'd1;
  localparam CMPLTTEST0_state = 4'd2;
  localparam CMPLTTEST1_state = 4'd3;
  localparam CMPLTTEST2_state = 4'd4;
  localparam CMPLTTEST3_state = 4'd5;
  localparam CMPLETEST0_state = 4'd6;
  localparam CMPLETEST1_state = 4'd7;
  localparam CMPLETEST2_state = 4'd8;
  localparam CMPLETEST3_state = 4'd9;
  localparam END_state = 4'd10;
  
  reg [3:0] M_state_d, M_state_q = CMPEQTEST0_state;
  
  reg [27:0] M_counter_d, M_counter_q = 1'h0;
  
  reg getNextState;
  
  reg resetFSM;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    testA = 1'h0;
    testB = 1'h0;
    alufn = 1'h0;
    resetFSM = reset;
    M_counter_d = M_counter_q + 1'h1;
    if (M_counter_q >= 28'hffffff0) begin
      getNextState = 1'h1;
    end else begin
      getNextState = 1'h0;
    end
    
    case (M_state_q)
      CMPEQTEST0_state: begin
        testA = 8'haa;
        testB = 8'haa;
        alufn = 6'h33;
        if (getNextState == 1'h1) begin
          if (alu == 8'h01) begin
            M_state_d = CMPEQTEST1_state;
          end
        end else begin
          M_state_d = CMPEQTEST0_state;
        end
      end
      CMPEQTEST1_state: begin
        testA = 8'haa;
        testB = 8'h55;
        alufn = 6'h33;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = CMPLTTEST0_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPEQTEST1_state;
        end
      end
      CMPLTTEST0_state: begin
        testA = 8'haa;
        testB = 8'haa;
        alufn = 6'h35;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = CMPLTTEST1_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLTTEST0_state;
        end
      end
      CMPLTTEST1_state: begin
        testA = 8'haa;
        testB = 8'h55;
        alufn = 6'h35;
        if (getNextState == 1'h1) begin
          if (alu == 8'h01) begin
            M_state_d = CMPLTTEST2_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLTTEST1_state;
        end
      end
      CMPLTTEST2_state: begin
        testA = 8'h55;
        testB = 8'haa;
        alufn = 6'h35;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = CMPLTTEST3_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLTTEST2_state;
        end
      end
      CMPLTTEST3_state: begin
        testA = 8'hff;
        testB = 8'h80;
        alufn = 6'h35;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = CMPLETEST0_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLTTEST3_state;
        end
      end
      CMPLETEST0_state: begin
        testA = 8'haa;
        testB = 8'haa;
        alufn = 6'h37;
        if (getNextState == 1'h1) begin
          if (alu == 8'h01) begin
            M_state_d = CMPLETEST1_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLETEST0_state;
        end
      end
      CMPLETEST1_state: begin
        testA = 8'haa;
        testB = 8'h55;
        alufn = 6'h37;
        if (getNextState == 1'h1) begin
          if (alu == 8'h01) begin
            M_state_d = CMPLETEST2_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLETEST1_state;
        end
      end
      CMPLETEST2_state: begin
        testA = 8'h55;
        testB = 8'haa;
        alufn = 6'h37;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = CMPLETEST3_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLETEST2_state;
        end
      end
      CMPLETEST3_state: begin
        testA = 8'hff;
        testB = 8'h80;
        alufn = 6'h37;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00) begin
            M_state_d = END_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = CMPEQTEST0_state;
            end
          end
        end else begin
          M_state_d = CMPLETEST3_state;
        end
      end
      END_state: begin
        testA = 8'h00;
        testB = 8'h00;
        alufn = 6'h00;
        if (getNextState == 1'h1) begin
          if (resetFSM == 1'h1) begin
            M_state_d = CMPEQTEST0_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
