/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mul_test_14 (
    input clk,
    input rst,
    input [7:0] alu,
    input [2:0] test,
    output reg [7:0] testA,
    output reg [7:0] testB,
    output reg [5:0] alufn,
    input reset
  );
  
  
  
  
  localparam MULTEST0_state = 3'd0;
  localparam MULTEST1_state = 3'd1;
  localparam MULTEST2_state = 3'd2;
  localparam MULTEST3_state = 3'd3;
  localparam END_state = 3'd4;
  
  reg [2:0] M_state_d, M_state_q = MULTEST0_state;
  
  reg [27:0] M_counter_d, M_counter_q = 1'h0;
  
  reg getNextState;
  
  reg resetFSM;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    testA = 1'h0;
    testB = 1'h0;
    alufn = 1'h0;
    resetFSM = reset;
    M_counter_d = M_counter_q + 1'h1;
    if (M_counter_q == 28'hfffffff) begin
      getNextState = 1'h1;
    end else begin
      getNextState = 1'h0;
    end
    
    case (M_state_q)
      MULTEST0_state: begin
        testA = 8'h10;
        testB = 8'h08;
        alufn = 6'h02;
        if (getNextState == 1'h1) begin
          if (alu == 8'h80 && test == 3'h0) begin
            M_state_d = MULTEST1_state;
          end
        end else begin
          M_state_d = MULTEST0_state;
        end
      end
      MULTEST1_state: begin
        testA = 8'h10;
        testB = 8'h10;
        alufn = 6'h02;
        if (getNextState == 1'h1) begin
          if (alu == 8'h00 && test == 3'h0) begin
            M_state_d = MULTEST2_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = MULTEST0_state;
            end
          end
        end else begin
          M_state_d = MULTEST1_state;
        end
      end
      MULTEST2_state: begin
        testA = 8'hff;
        testB = 8'h02;
        alufn = 6'h02;
        if (getNextState == 1'h1) begin
          if (alu == 8'hfe && test == 3'h0) begin
            M_state_d = MULTEST3_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = MULTEST0_state;
            end
          end
        end else begin
          M_state_d = MULTEST2_state;
        end
      end
      MULTEST3_state: begin
        testA = 8'hff;
        testB = 8'hfe;
        alufn = 6'h02;
        if (getNextState == 1'h1) begin
          if (alu == 8'h02 && test == 3'h0) begin
            M_state_d = END_state;
          end else begin
            if (resetFSM == 1'h1) begin
              M_state_d = MULTEST0_state;
            end
          end
        end else begin
          M_state_d = MULTEST3_state;
        end
      end
      END_state: begin
        testA = 8'h00;
        testB = 8'h00;
        alufn = 6'h00;
        if (getNextState == 1'h1) begin
          if (resetFSM == 1'h1) begin
            M_state_d = MULTEST0_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
