/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module test_rig_5 (
    input clk,
    input rst,
    input [7:0] alu,
    input [2:0] test,
    input [2:0] selector,
    output reg [7:0] testA,
    output reg [7:0] testB,
    output reg [5:0] alufn,
    input reset
  );
  
  
  
  reg [2:0] select;
  
  wire [8-1:0] M_adderTest_testA;
  wire [8-1:0] M_adderTest_testB;
  wire [6-1:0] M_adderTest_alufn;
  adder_test_13 adderTest (
    .clk(clk),
    .rst(rst),
    .alu(alu),
    .test(test),
    .reset(reset),
    .testA(M_adderTest_testA),
    .testB(M_adderTest_testB),
    .alufn(M_adderTest_alufn)
  );
  
  wire [8-1:0] M_mulTest_testA;
  wire [8-1:0] M_mulTest_testB;
  wire [6-1:0] M_mulTest_alufn;
  mul_test_14 mulTest (
    .clk(clk),
    .rst(rst),
    .alu(alu),
    .test(test),
    .reset(reset),
    .testA(M_mulTest_testA),
    .testB(M_mulTest_testB),
    .alufn(M_mulTest_alufn)
  );
  
  wire [8-1:0] M_booleTest_testA;
  wire [8-1:0] M_booleTest_testB;
  wire [6-1:0] M_booleTest_alufn;
  boole_test_15 booleTest (
    .clk(clk),
    .rst(rst),
    .alu(alu),
    .test(test),
    .reset(reset),
    .testA(M_booleTest_testA),
    .testB(M_booleTest_testB),
    .alufn(M_booleTest_alufn)
  );
  
  wire [8-1:0] M_shiftTest_testA;
  wire [8-1:0] M_shiftTest_testB;
  wire [6-1:0] M_shiftTest_alufn;
  shift_test_16 shiftTest (
    .clk(clk),
    .rst(rst),
    .alu(alu),
    .reset(reset),
    .testA(M_shiftTest_testA),
    .testB(M_shiftTest_testB),
    .alufn(M_shiftTest_alufn)
  );
  
  wire [8-1:0] M_cmpTest_testA;
  wire [8-1:0] M_cmpTest_testB;
  wire [6-1:0] M_cmpTest_alufn;
  cmp_test_17 cmpTest (
    .clk(clk),
    .rst(rst),
    .alu(alu),
    .reset(reset),
    .testA(M_cmpTest_testA),
    .testB(M_cmpTest_testB),
    .alufn(M_cmpTest_alufn)
  );
  
  always @* begin
    testA = 1'h0;
    testB = 1'h0;
    alufn = 1'h0;
    select = selector;
    if (select == 3'h0) begin
      testA = M_adderTest_testA;
      testB = M_adderTest_testB;
      alufn = M_adderTest_alufn;
    end else begin
      if (select == 3'h1) begin
        testA = M_mulTest_testA;
        testB = M_mulTest_testB;
        alufn = M_mulTest_alufn;
      end else begin
        if (select == 3'h2) begin
          testA = M_booleTest_testA;
          testB = M_booleTest_testB;
          alufn = M_booleTest_alufn;
        end else begin
          if (select == 3'h3) begin
            testA = M_shiftTest_testA;
            testB = M_shiftTest_testB;
            alufn = M_shiftTest_alufn;
          end else begin
            if (select == 3'h4) begin
              testA = M_cmpTest_testA;
              testB = M_cmpTest_testB;
              alufn = M_cmpTest_alufn;
            end
          end
        end
      end
    end
  end
endmodule
